"""Approved asset, voice identity, H3 publication, and Wan references."""

from .bundle import (
    AssetBundleError,
    apply_asset_approvals,
    assess_asset_readiness,
    build_pending_asset_bundle,
    load_bindings,
    load_bundle,
    prepared_content_digest,
    write_bundle,
)
from .models import (
    ASSET_BUNDLE_SCHEMA_VERSION,
    ApprovedAssetBundle,
    ApprovedReferenceAsset,
    AssetReadinessIssue,
    AssetReadinessReport,
    VoiceIdentityProfile,
)
from .publication import (
    H3_ASSET_PUBLICATION_SCHEMA_VERSION,
    H3AssetPublicationError,
    H3AssetPublicationPreflight,
    H3PublishedAssetManifest,
    OSSH3AssetPublisher,
    PublishedH3Asset,
    build_h3_asset_publication_preflight_for_episode as build_h3_asset_publication_preflight,
    materialize_h3_canary_asset_manifest,
    publish_h3_assets,
)
from .wan_references import (
    WAN_MASTER_REFERENCE_SCHEMA_VERSION,
    WanMasterReference,
    WanMasterReferenceError,
    WanMasterReferenceManifest,
    build_wan_master_reference_manifest,
    load_wan_master_reference_manifest,
    verify_wan_master_reference_manifest,
    write_wan_master_reference_manifest,
)

__all__ = [
    "ASSET_BUNDLE_SCHEMA_VERSION",
    "H3_ASSET_PUBLICATION_SCHEMA_VERSION",
    "WAN_MASTER_REFERENCE_SCHEMA_VERSION",
    "ApprovedAssetBundle",
    "ApprovedReferenceAsset",
    "AssetBundleError",
    "AssetReadinessIssue",
    "AssetReadinessReport",
    "H3AssetPublicationError",
    "H3AssetPublicationPreflight",
    "H3PublishedAssetManifest",
    "OSSH3AssetPublisher",
    "PublishedH3Asset",
    "VoiceIdentityProfile",
    "WanMasterReference",
    "WanMasterReferenceError",
    "WanMasterReferenceManifest",
    "apply_asset_approvals",
    "assess_asset_readiness",
    "build_h3_asset_publication_preflight",
    "build_pending_asset_bundle",
    "build_wan_master_reference_manifest",
    "load_bindings",
    "load_bundle",
    "load_wan_master_reference_manifest",
    "materialize_h3_canary_asset_manifest",
    "prepared_content_digest",
    "publish_h3_assets",
    "verify_wan_master_reference_manifest",
    "write_bundle",
    "write_wan_master_reference_manifest",
]
